### ISSUE TITLE
Link schema not used with <a> markup : print them directly

### ISSUE THREAD

**Issue by maieul** [gjtorikian/html-pipeline#194]
Actually, onlye some link schem are used when a .md become a .html.

For example link starting by `http://`  are allowed, but not these starting by `ftp://`.

Independently of the question to extend to some specific schem (in my sens `irc://` and `http://` should be extented), could it be possible to print the link event without using `<a href="...">` markup? Because now, the link is totally lost...

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
