### ISSUE TITLE
Use gemojione instead of gemoji

### ISSUE THREAD

**Issue by balasankarc** [gjtorikian/html-pipeline#200]
Hi,
gemojione is a free licensed collection of emoji. Can html-pipeline use that for EmojiFilter?

I am packaging html-pipeline for Debian as part of GitLab packaging and it hit a roadblock due to the non-free nature of gemoji. It would be a great help if this dependency on gemoji can be removed.

Thanks.

**Comment by jch** [comment]
@balasankarc that's a good suggestion, but would break old versions. Have you considered writing your own filter that depends on gemojione?

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. 

`gemojione` is now a supported dependency through the new `require_dependencies` method available to filters, which goes down a list of dependencies and selects the first one available: https://github.com/gjtorikian/html-pipeline/blob/dcf38a2371f20fd645d21d4d94cd7de14f249e7c/lib/html_pipeline/node_filter/emoji_filter.rb#L4
