### ISSUE TITLE
PHP syntax highlight

### ISSUE THREAD

**Issue by pyromaniackeca** [gjtorikian/html-pipeline#212]
The syntax highlight filter doesn't recognize php code without `<?php` at the start.
I did a little digging and have gotten the feeling that this is an issue with GitHub linguist, but since I am using that gem trough your gem I would prefer to check with you guys first.

I have created a repo with a rails app that demonstrates the issue, you can take a look [here](https://github.com/pyromaniackeca/github-linguist-test).

And the reason I consider this an issue is because GitHub highlights the same code when viewing it on their site, as shown:
![screen shot 2015-08-07 at 5 11 13 pm](https://cloud.githubusercontent.com/assets/1999881/9138959/59ea4486-3d27-11e5-8307-5592a860fc47.png)

Can you please assist or confirm that I need to take this up with github/linguist?

**Comment by gjtorikian** [comment]
Just going through old issues--if this is a problem with rendering on GitHub, please contact their Support, as they no longer use this gem.
