### ISSUE TITLE
Please document how to use the html-pipeline binary without command‐line arguments!

### ISSUE THREAD

**Issue by ytrezq** [gjtorikian/html-pipeline#213]
Something like a manpage or info page would be welcome. However I don’t understand at all how to use it.

**Comment by JuanitoFatas** [comment]
We have a [usage](https://github.com/jch/html-pipeline#usage) section in our README. Does this help?

**Comment by JuanitoFatas** [comment]
>  Please document how to use the html-pipeline binary without arguments! to Please document how to use the html-pipeline binary without command‐line arguments! 

I see.

@jch This script committed in https://github.com/jch/html-pipeline/commit/5e9688fc0862a3a07a45a1433ab61ceecaeb31c3. But we did have a `spec.executables` entry in `gemspec`. 

@ytrezq If you want to use it now, we did not package in the gem, you will need to download it to your machine, store in any of your `$PATH`. Usage can see by typing `html-pipeline -h`:

```
$ html-pipeline -h
Usage: html-pipeline [-h] [-f]
       html-pipeline [FILTER [FILTER [...]]] < file.md
       cat file.md | html-pipeline [FILTER [FILTER [...]]]
Options:
    -f, --filters                    List the available filters
```

If you already know how to use it and asking for documentations, would you mind open a Pull Request? 

 Hope this helps. Thank you!

**Comment by ytrezq** [comment]
I was talking about this script since the beginning. So no, this doesn’t help and I still don’t understand to use the standalone mode without filter names *(`sh -c "$PWD/html-pipeline"`)*.

I mind opening a pull request about a non‑security bug in a sanitizer that require line by. However I’m currently unable to reproduce it by calling commands like`sh -c "$PWD/html-pipeline [FILTER [FILTER [...]]] < file.md"`which all return the correct behaviour.

Or where is the code responsible for escaping the content between two disabled html tags ?

**Comment by gjtorikian** [comment]
Old issue, not sure what's being asked, please reopen if there's still and issue.

**Comment by ytrezq** [comment]
@gjtorikian as the original poster I can reopen this issue. Please do it.

As explained there s absolutely no help text explained is to do be able to use `html-pipeline` with default, options. That is, without optional filters.
