### ISSUE TITLE
'lexer' is removed from github-linguist

### ISSUE THREAD

**Issue by aptx4869** [gjtorikian/html-pipeline#217]
We get a

```
NoMethodError:
       undefined method `lexer' for #<Linguist::Language name=Ruby>
```

since github/linguist@5d0e9484ce9a3c1ae22637cfc61bda088a74c315 the `lexer' api is no longer exists
Should we change

``` ruby
(Linguist::Language[lang] && Linguist::Language[lang].lexer) || Pygments::Lexer[lang]
```

into

``` ruby
 (Linguist::Language[lang] && Linguist::Language[lang].try(:lexer)) || Pygments::Lexer[lang]
```

or add some code to check github-linguist version?

**Comment by jch** [comment]
That fallback is already pretty confusing, so I'd rather not add another `try` to the mix. We could update the [warning at the require](https://github.com/jch/html-pipeline/blob/74185f6b8f0774d5d490c10b5593d64ca6f16f08/lib/html/pipeline/syntax_highlight_filter.rb#L1-L5), but it would still error out early. It's tricky because we don't require explicit versions for linguist.

**Comment by royzinn** [comment]
Hi,
So, from the above, what would be the better solution to keep using SyntaxHighlighter? should I move to some specific earlier version of Linguist or is there another solution?
Thanks in advance

**Comment by jch** [comment]
@aptx4869 I haven't come up with a better way to address this, so in the interest of maintaining semver, would you be up for creating a PR with your fix?

@royzinn as a temporary fix, I suggest applying @aptx4869's changes locally to your project. Alternatively, you can use an older version of linguist.

**Comment by bmikol** [comment]
Alternatively, you could also just use the [HTML::Pipeline-rouge_filter](https://github.com/JuanitoFatas/html-pipeline-rouge_filter) - it's been working great for me.

**Comment by jch** [comment]
@bmikol :+1: totally forgot about that one.

**Comment by royzinn** [comment]
@bmikol @jch - thanks both! it works for me with rouge filter

**Comment by gjtorikian** [comment]
Old issue
