### ISSUE TITLE
What’s the point of allowing the accept-charset attribute in the sanitization filter ?

### ISSUE THREAD

**Issue by ytrezq** [gjtorikian/html-pipeline#218]
Isn’t the`accept-charset`attribute only used with the`form`element which is not allowed ?
The same apply for the`method`attribute.

There is also the point of allowing the`usemap`attribute without the map element.

**Comment by gjtorikian** [comment]
`accept-charset` is used for more than just forms.

**Comment by ytrezq** [comment]
@gjtorikian what about usemap?

**Comment by gjtorikian** [comment]
Seems sane enough to include in v3.

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
