### ISSUE TITLE
Allow ᴀʀɪᴀ attributes for blind people.

### ISSUE THREAD

**Issue by ytrezq** [gjtorikian/html-pipeline#219]
Those attributes are purely informative. [ᴍᴅɴ documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA).

**Comment by gjtorikian** [comment]
Old issue, `aria-*` attributes have been in for a while.

**Comment by ytrezq** [comment]
@gjtorikian is the issue fixed?
