### ISSUE TITLE
Require pygments.rb or remove Pygments references

### ISSUE THREAD

**Issue by nbibler** [gjtorikian/html-pipeline#235]
In `github-linguist` version 4, the [`pygments.rb` dependency was removed](https://github.com/github/linguist/pull/1707). The following code relies on the idea that _some other dependency_ (linguist at the time) is requiring pygments:

``` ruby
def lexer_for(lang)
  (Linguist::Language[lang] && Linguist::Language[lang].lexer) || Pygments::Lexer[lang]
end
```

Since linguist no longer loads pygments, but html-pipeline makes an assumption that it's loaded, this breaks unless the dev adds a pygments requirement somewhere in their calling application and Gemfile.

**Comment by gjtorikian** [comment]
Old issue, pygments is gone
