### ISSUE TITLE
Allow RDFa 1.1 (Lite) attributes

### ISSUE THREAD

**Issue by alexmilowski** [gjtorikian/html-pipeline#249]
It would really be great to allow the various RDFa 1.1 Lite attributes so RDFa-enabled content can be embedded in Markdown pages.

The attributes are 'vocal', 'typeof', 'property', 'resource', and 'prefix'.  They should be allowed on any element.

Because they have no operational semantics for HTML browsers, they should be fairly harmless.

**Comment by alexmilowski** [comment]
...and happy to write the patch to do so.

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
