### ISSUE TITLE
Allow SVG elements in whitelist

### ISSUE THREAD

**Issue by chrisknoll** [gjtorikian/html-pipeline#251]
Would like to pop some SVG into markdown, but it doesn't appear to be in the whitelist:

https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L44-L106

Is there a limitation to SVG tag support?

-Chris

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
