### ISSUE TITLE
Consider allowing LINK and META elements in HTML

### ISSUE THREAD

**Issue by lucboudreau** [gjtorikian/html-pipeline#261]
We would like this community to consider allowing the LINK and META HTML elements in GitHub markdown. As far as I can tell, they are [not currently allowed](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L44-L106).

These are necessary in order to add GMail message actions, as [documented here](https://developers.google.com/gmail/markup/reference/go-to-action). These links are very useful when the comments are generated by a system which uses the GitHub statuses API to validate commits and pull requests.

I'm not a HTML expert, so I will leave it to this group to discuss the implication of allowing those.

NB. We have also created an [issue on the GitHub Markup project](https://github.com/github/markup/issues/912) for this discussion to happen.

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
