### ISSUE TITLE
Open link in new tab option

### ISSUE THREAD

**Issue by kenold** [gjtorikian/html-pipeline#266]
Please add option to open link in new tab and add a target variable in _config.yml

```
jekyll-mentions:
  target: blank
```

**Comment by emma-sax4** [comment]
I would also appreciate this as an option.

**Comment by emma-sax4** [comment]
@kenold I'm not sure if this is still something that you'd like, but I'm working on a fork of this to make this option a thing: https://github.com/emma-sax4/html-pipeline/pull/1.

**Comment by DhanabakiyamS** [comment]
tarket=_blank

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I think it's outside the scope of the project. You can create your own NodeFilter to add this attribute though; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#nodefilters).
