### ISSUE TITLE
A filter to produce diffs with syntax highlighting in html, maybe.

### ISSUE THREAD

**Issue by akashdotsrivastava** [gjtorikian/html-pipeline#270]
I'm currently looking at various options for producing code difference (side-by-side/inline) with syntax highlighting (based on language). One option I'm using for most of my needs is Redcarpet/Coderay with Diffy, but I am sanitizing the intermediate html, produced by either of the   layers (difference/highlighting) first, before putting the next layer, so looking for a cleaner way. Also the results are not that great when it comes to viewing. So just dropping this as an issue here, as the Readme suggests, for a filter.

**Comment by gjtorikian** [comment]
I'm not sure this is a common enough use case to include in the gem, sorry.
