### ISSUE TITLE
alt Attribute for Emoji Images Should Use Unicode

### ISSUE THREAD

**Issue by Crissov** [gjtorikian/html-pipeline#272]
Copying emojis from Github and pasting them into Unicode-aware applications that do not support (proprietary) short codes with colons is currently broken.

In [emoji_filter.rb](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/emoji_filter.rb#L90):

```` ruby
      # Default attributes for img tag
      def default_img_attrs(name)
        {
          "class" => "emoji".freeze,
          "title" => ":#{name}:",
          "alt" => ":#{name}:",
          "src" => "#{emoji_url(name)}",
          "height" => "20".freeze,
          "width" => "20".freeze,
          "align" => "absmiddle".freeze,
        }
      end
````

The alternative textual representation of an image of a Unicode emoji is of course the emoji itself! Therefore, line 90 should read something like this: `"alt" => "#{code}",` or `"alt" => "#{emoji_code(name)}",`, probably using [`unicode_aliases.first`](https://github.com/github/gemoji/blob/master/lib/emoji/character.rb#L37) from gemoji. 

Custom "emojis" should probably use ``#{name}` without colons.

My ruby-fu is sadly not up for the task, so I'm not providing a PR.

**Comment by gjtorikian** [comment]
Thanks for the report. I believe as of https://github.com/gjtorikian/html-pipeline/pull/373 this is moot for v3.0+.
