### ISSUE TITLE
Allow float: left|right and clear: left|right|both in sanitation

### ISSUE THREAD

**Issue by flying-sheep** [gjtorikian/html-pipeline#302]
`align="..."` is deprecated and the non-deprecated alternative is using CSS. however, the sanitation filter strips inline CSS. There should be an exception for this.

If this issue is not fixed, github/markup#163 can never be fixed (it has been closed without proper reason and should be open), and github/markup#1222 can never be finished.

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
