### ISSUE TITLE
code in header produce invalid anchor

### ISSUE THREAD

**Issue by ghost** [gjtorikian/html-pipeline#308]
If you use some markup like this:

~~~
`aaaaa`
-------

bbbbb
~~~

I would expect this result:

~~~
#aaaaa
~~~

however what is generated is:

~~~
#codeaaaaacode
~~~

https://github.com/jch/html-pipeline/blob/af66272dc34e13f48fff97c3b7b42e64e82877f2/lib/html/pipeline/toc_filter.rb#L28-L64

**Comment by cup** [comment]
https://github.com/github/jekyll-commonmark-ghpages/issues/10
https://github.com/gjtorikian/commonmarker/issues/93
https://github.com/jch/html-pipeline/issues/308

**Comment by gjtorikian** [comment]
Old issue
