### ISSUE TITLE
Feature request: add safe semantic HTML tags to default whitelist

### ISSUE THREAD

**Issue by aviflax** [gjtorikian/html-pipeline#312]
Including, but not necessarily limited to:

* [`address`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address)
* [`article`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article)
* [`aside`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside)
* [`footer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer)
* [`header`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)
* [`main`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main)
* [`section`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)

and maybe [`nav`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav)?

I don’t know if I need to make the case for the value and safety of these tags? Personally I just really ❤️ semantic markup, it makes my :neckbeard: self happy. But if anyone asks “why” I’ll dig up some good links to make the case.

Thanks!

**Comment by gjtorikian** [comment]
A new (beta) release of HTML-Proofer has been released, v3.0.0.pre1. I tried to go back and address all the issues in this repo. For this specific issue, I've opted to keep the sanitization process the same. However, downstream consumers can easily make any change they want to the sanitization process; see [the updated README for more information](https://github.com/gjtorikian/html-pipeline#sanitization).
