### ISSUE TITLE
2.14.0 is disconnected

### ISSUE THREAD

**Issue by duck-rh** [gjtorikian/html-pipeline#358]
Quack,

I was trying to get the full list of changes in this version to debug tests that do not behave as expected (supposedly working fine with 2.13.2), but I could not find it in `CHANGELOG.md`. In the list of releases I could only find the Rinku change but wanted to look at the list of commits and went to the tag to find this warning: _This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository_. Therefore it seems you forgot to push all the changes in the main branch. Btw in `CHANGELOG.md` for this commit there is no reference to this version either.

Could you have a look please?

\\_o<

**Comment by gjtorikian** [comment]
I'm not sure this issue is accurate, the rinku change is committed right here: https://github.com/gjtorikian/html-pipeline/commit/5d76e286fffbbd14d65fbba152c0c3caab0a55f6

**Comment by duck-rh** [comment]
Right, if I check the parent commits I can get the history. I just can't fathom what would be the rationale for not pushing these changes in the main branch. In fact that makes 2.14 a regression since all the fixes in 2.13.1 and 2.13.2 are not included. And again the changelog was not updated, which was my original motivation to look into all this.

The goal of this ticket is not to criticize your project management, I'm genuinely lost.

**Comment by gjtorikian** [comment]
Oh, wow, you're right—I see the problem now. 2.14 was tagged Aug 11, 2020 and 2.13.2 was Dec 4, 2020. That's definitely not intentional and unintended.

**Comment by duck-rh** [comment]
Ok, glad we found out :-)

There's nothing that can be done for 2.14 since it's already released and re-releasing with the same version would be confusing. I would suggest making a 2.14.1 when you have time.
