### ISSUE TITLE
Allow `loading` attribute on images

### ISSUE THREAD

**Issue by elidrissidev** [gjtorikian/html-pipeline#359]
Currently, it seems that the loading attribute isn't allowed for images. This is especially useful if you visit a repository with a README.md that contains a lot of images while on a metered connection.

I can contribute a PR if this is something to be considered.

**Comment by fballiano** [comment]
any news on this?

**Comment by elidrissidev** [comment]
I figure this is gonna take ages to propagate to GitHub, even if implemented here.

**Comment by gjtorikian** [comment]
GitHub no longer uses this gem; it's just a plain old open source project manage by one person.

**Comment by fballiano** [comment]
do you know where can we open this same issue?

**Comment by gjtorikian** [comment]
There's a product feedback link at https://github.com/community/community/discussions, that might work!
