### ISSUE TITLE
v3 gemoji, gemojione seem required - is there a way to not require at puma startup?

### ISSUE THREAD

**Issue by mrthan** [gjtorikian/html-pipeline#376]
Migrating from v2 to v3, using MarkdownFilter and I can't figure NOT having emojis. Is there something I'm missing with these? I just want markdown without emojis and don't want to include either of these gems.

```
ruby/3.2.0/lib/ruby/gems/3.2.0/gems/html-pipeline-3.0.0.pre3/lib/html_pipeline.rb:76:in `rescue in require_dependencies': Missing all dependencies 'gemoji, gemojione' for EmojiFilter. See README.md for details. (HTMLPipeline::MissingDependencyError)
LoadError: cannot load such file -- gemojione
```

**Comment by gjtorikian** [comment]
This is most definitely a bug. Could you show me how your pipeline is being set up so that I can reproduce it? Looking at the code I'm not seeing how this is immediately possible, but it shouldn't be happening!

**Comment by gjtorikian** [comment]
Closing to clean up my queue, feel free to reopen with a repro.
