### ISSUE TITLE
Can't seem to get a <script> to run when added to the allowlist?

### ISSUE THREAD

**Issue by chrismahon** [gjtorikian/html-pipeline#399]
I'm trying to allow for a <script> tag to run as it would normally if you were to include it in a HTML file. I know the security concerns associated with this, but there is a specific use case the markdown editor has that requires us to be able to include <script> tags.

I have the following code example:

```
  def render
    pipeline = HTMLPipeline.new \
      convert_filter: HTMLPipeline::ConvertFilter::MarkdownFilter.new,
      sanitization_config: sanitization_config
    result = pipeline.call("<script>console.log(1)</script>")
    result[:output].html_safe
  end
  
  def sanitization_config
    config = HTMLPipeline::SanitizationFilter::DEFAULT_CONFIG.deep_dup
    config[:elements] << "script"
    config
  end
```

Is there something I am missing with the sanitisation_config so the `console.log(1)` fires correctly in the dev console?

**Comment by gjtorikian** [comment]
waiting to hear back
